### ISSUE TITLE
Potential bug, safeTramsferForm() could be missing in some exsting tokens

### ISSUE THREAD

**Issue by chiro-hiro** [DecenterApps/defisaver-contracts#46]
https://github.com/DecenterApps/defisaver-contracts/blob/master/contracts/compound/CompoundBasicProxy.sol#L25

It might need to be `transferForm()`

**Comment by nklipa13** [comment]
We are using [SafeERC20.sol](https://github.com/DecenterApps/defisaver-contracts/blob/master/contracts/utils/SafeERC20.sol) as library for ERC20 as you can see [here](https://github.com/DecenterApps/defisaver-contracts/blob/1208a980c2f6630fd1e9e73ad3dfba78d82597de/contracts/compound/CompoundBasicProxy.sol#L15)

This library handles both old and new implementation of ERC20, in the old implementation methods didn't have return parameters, while new ERC20 implementations return bool as a success.

**Comment by chiro-hiro** [comment]
Thank you, I got it.
